#!/bin/bash

if [ -z "${1// }" ]; then
  echo "alsa-rec: record alsa sound (midi output)"
  echo "Need to provide a file name to save as (e.g. out.wav)";
  exit 1;
fi

sox -t alsa default "$1" silence 1 0.1 5% 1 1.0 5%
