#!/bin/bash
available=$(/usr/bin/cower -u)
if [ $? != 0 ]; then
    /usr/bin/notify-send -u critical \
                "AUR Updates Available" \
                "Run 'trizen -Su --aur' to update all. Updates available:\n$available"
fi
