#!/usr/bin/env python3
import re
import subprocess


def get_available_updates():
    p = subprocess.run(['/usr/bin/trizen', '-Syu', '--aur'],
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE,
                       check=True)

    lines = p.stdout.decode('utf8').splitlines()
    available = []
    for line in lines:
        if line.startswith('::'):
            continue
        if re.match(r'^\s*(\d+)\.\s+([^:]+):.*', line):
            available.append(line)
    return available


def main():
    available = get_available_updates()
    if available:
        subprocess.run([
            '/usr/bin/notify-send', '-u', 'critical', 'AUR Updates Available',
            ("Run 'trizen -Su --aur' to update all:\n" + '\n'.join(available))
        ],
                       check=True)


if __name__ == '__main__':
    main()
